### ISSUE TITLE
to do - code 1000 times

### ISSUE THREAD

**Issue by kmkaur** [kmkaur/coevolver#13]
https://github.com/kmkaur/coevolver/blob/ff17ec8ac52d45dd937a14e3afd6d533daeff374/R/Burn-in_function.R#L108

**Comment by kmkaur** [comment]
the fxn works, but saving each one to its own file currently not working
https://github.com/kmkaur/coevolver/blob/ff0bb78141a2591ad9f1b7db515dc218ff4f5035/R/Burn-in_function.R#L114

**Comment by mwpennell** [comment]
messed up. should be
```
  saveRDS(out, paste0("out/mutualism_matching_sim_", iter, ".rds"))
```

**Comment by kmkaur** [comment]
dir.create("out") also added
